# Bài tập về nhà 1
### Môn: Linear Algebra

In [1]:
import numpy as np

### Bài 1 - Dãy số co
Bắt đầu với một dãy $S=(a_1,\dots,a_{8})$ gồm 8 số nguyên dương phân biệt, được chọn ngẫu nhiên trong đoạn $[1,300]$ và tìm chuỗi 

$$S_1=T(S)=(|a_1-a_{2}|,\dots,|a_{7}-a_{8}|,|a_{8}-a_{1}|)$$

Các dãy $S,\,S_1,\,S_2=T(S_1),S_3=T(S_2),\dots$ có kết thúc bởi dãy $(0,\dots,0)$ hay không? Hãy tìm câu trả lời bằng cách xây dựng mảng 2-chiều $A$ có hàng $A[i]$ là dãy $S_i$, hàng cuối cùng của mảng $A$ tương ứng với dãy số 0.

### Lời giải

In [11]:
S = np.zeros(8,dtype=np.int64)
for i in range(8):
    while True:
        x = np.random.randint(1,300)
        if x not in S:
            S[i]=x
            break
S

array([ 79, 288,  63, 113, 215,  98, 238, 265], dtype=int64)

In [12]:
def transform(s):
    n=len(s)
    s1=np.zeros(8,dtype=np.int64)
    for i in range(n-1):
        s1[i]=np.abs(s[i]-s[i+1])
    s1[-1]=np.abs(s[-1]-s[0])
    return s1

A=S
for row in range(20):
    S=transform(S)
    A=np.vstack([A,S])
A

array([[ 79, 288,  63, 113, 215,  98, 238, 265],
       [209, 225,  50, 102, 117, 140,  27, 186],
       [ 16, 175,  52,  15,  23, 113, 159,  23],
       [159, 123,  37,   8,  90,  46, 136,   7],
       [ 36,  86,  29,  82,  44,  90, 129, 152],
       [ 50,  57,  53,  38,  46,  39,  23, 116],
       [  7,   4,  15,   8,   7,  16,  93,  66],
       [  3,  11,   7,   1,   9,  77,  27,  59],
       [  8,   4,   6,   8,  68,  50,  32,  56],
       [  4,   2,   2,  60,  18,  18,  24,  48],
       [  2,   0,  58,  42,   0,   6,  24,  44],
       [  2,  58,  16,  42,   6,  18,  20,  42],
       [ 56,  42,  26,  36,  12,   2,  22,  40],
       [ 14,  16,  10,  24,  10,  20,  18,  16],
       [  2,   6,  14,  14,  10,   2,   2,   2],
       [  4,   8,   0,   4,   8,   0,   0,   0],
       [  4,   8,   4,   4,   8,   0,   0,   4],
       [  4,   4,   0,   4,   8,   0,   4,   0],
       [  0,   4,   4,   4,   8,   4,   4,   4],
       [  4,   0,   0,   4,   4,   0,   0,   4],
       [  4,   0,   

### Bài 2 - Tam giác Pascal
Tạo một mảng 2-chiều kích thước $10\times 10$. Mảng được chia thành hai hình tam giác đối xứng qua đường chéo phụ (*xem hình vẽ trong phiếu bài tập về nhà*), trong đó hình tam giác (nửa mảng) gồm các phần tử tạo thành tam giác Pascal.

### Lời giải

In [13]:
A = np.zeros((10,10),dtype=np.int64)
for i in range(10):
    A[0,i] = A[i,0] = A[9,i] = A[i,9] = 1
for i in range(10):
    for j in range(8-i):
        A[i+1,j+1] = A[i,j+1] + A[i+1,j]
print(A)
for i in range(1,9):
    for j in range(1,9-i):
        A[9-i,9-j] = A[i,j]
A

[[  1   1   1   1   1   1   1   1   1   1]
 [  1   2   3   4   5   6   7   8   9   1]
 [  1   3   6  10  15  21  28  36   0   1]
 [  1   4  10  20  35  56  84   0   0   1]
 [  1   5  15  35  70 126   0   0   0   1]
 [  1   6  21  56 126   0   0   0   0   1]
 [  1   7  28  84   0   0   0   0   0   1]
 [  1   8  36   0   0   0   0   0   0   1]
 [  1   9   0   0   0   0   0   0   0   1]
 [  1   1   1   1   1   1   1   1   1   1]]


array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,   1],
       [  1,   3,   6,  10,  15,  21,  28,  36,   8,   1],
       [  1,   4,  10,  20,  35,  56,  84,  28,   7,   1],
       [  1,   5,  15,  35,  70, 126,  56,  21,   6,   1],
       [  1,   6,  21,  56, 126,  70,  35,  15,   5,   1],
       [  1,   7,  28,  84,  56,  35,  20,  10,   4,   1],
       [  1,   8,  36,  28,  21,  15,  10,   6,   3,   1],
       [  1,   9,   8,   7,   6,   5,   4,   3,   2,   1],
       [  1,   1,   1,   1,   1,   1,   1,   1,   1,   1]], dtype=int64)