# Bài tập về nhà 5
### Môn: Linear Algebra

In [1]:
import numpy as np

### Bài tập 1
Cho $U\subset\mathbb{R}^6$ và ${\bf x}\in\mathbb{R}^5$ như sau:
$$U=\mathrm{span}\left\{\left[\begin{matrix}
0 \\
-1 \\
2 \\
0 \\
2
\end{matrix}\right],\,\left[\begin{matrix}
1 \\
-3 \\
1 \\
-1 \\
2
\end{matrix}\right],\,\left[\begin{matrix}
-3 \\
4 \\
1 \\
2 \\
1
\end{matrix}\right],\,\left[\begin{matrix}
-1 \\
-3 \\
5 \\
0 \\
7
\end{matrix}\right]\right\},\,{\bf x}=\left[\begin{matrix}
-1 \\
-9 \\
-1 \\
4 \\
1
\end{matrix}\right]$$
* Xác định hình chiếu trực giao của $\bf x$ trên $U$.
* Tính khoảng cách $d({\bf x},U)$.

In [5]:
u1 = np.array([0,-1,2,0,2])
u2 = np.array([1,-3,1,-1,2])
u3 = np.array([-3,4,1,2,1])
u4 = np.array([-1,-3,5,0,7])

# Thủ tục Gram-Schmidt
X = np.vstack([u1,u2,u3,u4])
n = len(X)
A = [X[0]]   # orthonormal set

# Trực giao hóa
for i in range(1,n):
    u = X[i].copy()
    for v in A:
        if v.any()!=0:
            u = np.around(u-(np.inner(u,v)/np.inner(v,v))*v,10)
    if u.any()!=0:
        A.append(u)

# Trực chuẩn hóa
for i in range(len(A)):
    v = A[i]
    A[i] = np.around(1/np.linalg.norm(v)*v,10)
A=np.array(A)

In [6]:
x = np.array([-1,-9,-1,4,1])
x_p = np.zeros(5)
for v in A:
    x_p +=np.dot(x,v)*v
print("Hình chiếu trực giao trên U:",x_p)

Hình chiếu trực giao trên U: [ 1. -5. -1. -2.  3.]


In [7]:
print('Khoảng cách từ x đến U:',np.linalg.norm(x-x_p))

Khoảng cách từ x đến U: 7.745966692492293


### Bài tập 2
Cho ma trận ${\bf A}=\left[\begin{matrix}
7 & -6 & -4 & 1\\
-5 & 1 & 0 & -2\\
10 & 11 & 7 & -3\\
19 & 9 & 7 & 1
\end{matrix}\right]$ và véc tơ 
${\bf b}=\left[\begin{matrix}
0.100\\
2.888\\
-1.404\\
1.462
\end{matrix}\right]$
* Thực hiện phân tích QR cho ma trận ${\bf A}$.
* Tìm nghiệm bình phương cực tiểu của ${\bf A}{\bf x}={\bf b}$ bằng phân tích QR.

In [8]:
A=np.array([[7,-6,-4,1],[-5,1,0,-2],[10,11,7,-3],[19,9,7,1]])
Q,R=np.linalg.qr(A)
print("Ma trận A, Q, R theo thứ tự:")
print(A,Q,R,sep="\n")

Ma trận A, Q, R theo thứ tự:
[[ 7 -6 -4  1]
 [-5  1  0 -2]
 [10 11  7 -3]
 [19  9  7  1]]
[[-0.30263639  0.77517596  0.55376724  0.02924522]
 [ 0.21616885 -0.27262274  0.45651534  0.81886606]
 [-0.4323377  -0.56683143  0.57814975 -0.39689936]
 [-0.82144163 -0.05900164 -0.38817324  0.41361092]]
[[-2.31300670e+01 -1.01167022e+01 -7.56590977e+00 -2.59402621e-01]
 [ 0.00000000e+00 -1.16898390e+01 -7.48153535e+00  2.96191410e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.85233376e-01 -2.48188591e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.17788805e-03]]


In [9]:
b=np.array([0.100,2.888,-1.404,1.462])
print("Nghiệm bình phương cực tiểu:",np.dot(np.dot(np.linalg.inv(R),Q.T),b))

Nghiệm bình phương cực tiểu: [   -8.642 -1730.054  2368.716  -844.866]
