# Thực hành

In [1]:
# Khai báo thư viện
import numpy as np

In [14]:
# Khởi tạo ma trận
A = np.array([1, -2, 4, 2, 5, 6]).reshape(2,3)
print(A)

I = np.eye(4,6,-1)
print(I)
np.identity(3)

[[ 1 -2  4]
 [ 2  5  6]]
[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# Tạo các ma trận khối: F = [[A | B], [C | D]]
A = np.zeros((2,2))
B = np.ones((2,2))
C = np.array([1,4,-2,5]).reshape(2,2)
D = np.arange(5,9).reshape(2,2)
F = np.vstack([np.hstack([A,B]), np.hstack([C,D])])
print(F)

[[ 0.  0.  1.  1.]
 [ 0.  0.  1.  1.]
 [ 1.  4.  5.  6.]
 [-2.  5.  7.  8.]]


In [18]:
d = [2, 1, 4, 5, 7]
np.diag(d,-1)

array([[0, 0, 0, 0, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 7, 0]])

In [21]:
A = np.random.randint(-5,6,(4,4))
print(A)
L = np.tril(A,-1)
U = np.triu(A,1)
D = np.diag(A)
print(L, U, D, sep='\n')

[[-2  5 -1 -5]
 [ 1  0 -4 -1]
 [ 3 -3  2  4]
 [ 1 -4 -4 -2]]
[[ 0  0  0  0]
 [ 1  0  0  0]
 [ 3 -3  0  0]
 [ 1 -4 -4  0]]
[[ 0  5 -1 -5]
 [ 0  0 -4 -1]
 [ 0  0  0  4]
 [ 0  0  0  0]]
[-2  0  2 -2]


In [24]:
# Hai ma trận bằng nhau
A = np.array([1,2,3,4]).reshape(2,2)
B = np.array([1,-2,3,4]).reshape(2,2)
np.all(A==B)
np.allclose(A, B)

False

In [30]:
# Nhân ma trận
A@B
np.matmul(A,B)
np.dot(A,B)
A.dot(B)

array([[ 7,  6],
       [15, 10]])

In [27]:
# Nhân từng phần tử (không phải phép nhân ma trận)
A*B

array([[ 1, -4],
       [ 9, 16]])

In [33]:
# Chuyển vị ma trận
A.T
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [34]:
# Luỹ thừa ma trận
np.linalg.matrix_power(A,2)

array([[ 7, 10],
       [15, 22]])

In [36]:
A**2 # luỹ thừa từng phần tử

array([[ 1,  4],
       [ 9, 16]])

In [38]:
# Tính det, rank
np.linalg.det(A)
np.linalg.matrix_rank(A)

2

## Phân tích ma trận

In [40]:
def MF(A, W, H, K, steps=1000, beta=0.002):
    m, n = A.shape
    for step in range(steps): # Bước lặp
        for i in range(m):    # Cập nhật lại ma trận W, H
            for j in range(n):
                if A[i,j]!=0:
                    eij = A[i,j] - W[i]@H[j]
                    for k in range(K):
                        W[i,k] += beta*(2*eij*H[j,k])
                        H[j,k] += beta*(2*eij*W[i,k])
        e = 0 # Tính tổng bình phương sai số
        for i in range(m):
            for j in range(n):
                if A[i,j]!=0:
                    e += (A[i,j] - W[i]@H[j])**2
        if e<1e-5: break  # Điều kiện dừng
    return W, H

In [44]:
X = np.array([5, 3, 0, 1,
              4, 0, 0, 1,
              1, 1, 0, 5,
              1, 0, 0, 4,
              0, 1, 5, 4]).reshape(5,4)
print(X)
M, N = X.shape
print(M, N)
K = 2
W = np.random.rand(M,K)
H = np.random.rand(N,K)
print(W,H)

[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]
5 4
[[0.47846541 0.03618668]
 [0.13980139 0.19028721]
 [0.75807516 0.80896103]
 [0.79842183 0.83586065]
 [0.52347808 0.29468221]] [[0.8362119  0.71729287]
 [0.14484484 0.06248009]
 [0.55718236 0.65234259]
 [0.74058364 0.10349727]]


In [50]:
W_, H_ = MF(X, W, H, K)
print(W_, H_)
W_@H_.T

[[0.8698584  2.34581299]
 [0.77700969 1.86242941]
 [2.12743549 0.14907109]
 [1.71868117 0.20991009]
 [1.74338547 0.32344677]] [[ 0.33381032  2.00773425]
 [ 0.37932859  1.13727354]
 [ 2.52301709  1.83109423]
 [ 2.38218724 -0.45722753]]


array([[5.00013678, 2.9977932 , 6.49007223, 0.9995953 ],
       [3.99863717, 2.41283369, 5.37069248, 0.99942857],
       [1.00945505, 0.97653171, 5.64051931, 4.99979027],
       [0.99515718, 0.8906701 , 4.72062712, 3.99824368],
       [1.23135522, 1.02916341, 4.99085284, 4.00518184]])