# Bài thực hành 5
### Môn: Linear Algebra

In [1]:
import numpy as np

### Bài tập 1
Cho các véc tơ ${\bf x}_1=\left[\begin{matrix}
1 \\
5 \\
-6\\
3
\end{matrix}\right],\,{\bf x}_2=\left[\begin{matrix}
-3 \\
11 \\
-9 \\
12
\end{matrix}\right],\,{\bf x}_3=\left[\begin{matrix}
-10 \\
9 \\
-4 \\
4
\end{matrix}\right]$ và ${\bf y}=\left[\begin{matrix}
0 \\
0 \\
0 \\
-1
\end{matrix}\right]$. 
* Hãy xây dựng một cơ sở trực giao cho $W=\mathrm{span}\{{\bf x}_1,{\bf x}_2,{\bf x}_3\}$.
* Tìm hình chiếu trực giao của $\bf y$ trên $W$

In [2]:
x1 = np.array([1,5,-6,3])
x2 = np.array([-3,11,-9,12])
x3 = np.array([-10,9,-4,4])

# Thủ tục Gram-Schmidt
X = np.vstack([x1,x2,x3])
n = len(X)
A = [X[0]]      # orthonormal set

# Trực giao hóa
for i in range(1,n):
    u = X[i].copy()
    for v in A:
        if v.any()!=0:
            u = np.around(u-(np.inner(u,v)/np.inner(v,v))*v,10)
    if u.any()!=0:
        A.append(u)

# Trực chuẩn hóa
for i in range(len(A)):
    v = A[i]
    A[i] = np.around(1/np.linalg.norm(v)*v,10)
A=np.array(A)

In [3]:
print('Cơ sở trực giao của W:')
for a in A:
    print(a)

Cơ sở trực giao của W:
[ 0.11867817  0.59339083 -0.71206899  0.3560345 ]
[-0.59339083  0.11867817  0.3560345   0.71206899]
[-0.71206899  0.3560345  -0.11867817 -0.59339083]


In [4]:
y = np.array([0,0,0,-1])
y_p = np.zeros(4)
for a in A:
    y_p +=np.dot(y,a)/np.inner(a,a)*a
print("Hình chiếu trực giao trên W:",y_p)

Hình chiếu trực giao trên W: [-0.04225352 -0.08450704 -0.07042254 -0.98591549]


### Bài tập 2

Cho ma trận: 
$${\bf A}=\left[\begin{matrix}
1 & 3 & -7\\
2 & 1 & 1\\
-2 & 7 & 11\\
9 & 11 & 3
\end{matrix}\right],\ 
{\bf b}=\left[\begin{matrix}
3\\
1\\
-1\\
3
\end{matrix}\right]$$
* Thực hiện phân tích QR cho ma trận ${\bf A}$.
* Tìm nghiệm bình phương cực tiểu của ${\bf A}{\bf x}={\bf b}$ bằng phân tích QR.
* Tìm một cơ sở trực chuẩn của không gian cột của $A$.

In [5]:
a=np.array([[1,3,-7],[2,1,1],[-2,7,11],[9,11,3]])
q,r=np.linalg.qr(a)
print("Ma trận A, Q, R theo thứ tự:")
print(a,q,r,sep="\n")

Ma trận A, Q, R theo thứ tự:
[[ 1  3 -7]
 [ 2  1  1]
 [-2  7 11]
 [ 9 11  3]]
[[-0.10540926  0.21081851  0.9486833 ]
 [-0.21081851 -0.10540926 -0.21081851]
 [ 0.21081851  0.9486833  -0.21081851]
 [-0.9486833   0.21081851 -0.10540926]]
[[-9.48683298 -9.48683298  0.        ]
 [ 0.          9.48683298  9.48683298]
 [ 0.          0.         -9.48683298]]


In [6]:
b=np.array([3,1,-1,3])
rinv=np.linalg.inv(r)
qt=q.T
print("Nghiệm:",np.dot(np.dot(rinv,qt),b))

Nghiệm: [ 0.08888889  0.28888889 -0.26666667]


In [7]:
print("Cơ sở trực chuẩn:")
for i in range(q.shape[1]):
    print(q[:,i])

Cơ sở trực chuẩn:
[-0.10540926 -0.21081851  0.21081851 -0.9486833 ]
[ 0.21081851 -0.10540926  0.9486833   0.21081851]
[ 0.9486833  -0.21081851 -0.21081851 -0.10540926]


### Bài 3 (Đo khoảng cách giữa các văn bản)

Mỗi văn bản được mô tả bởi 1 véc tơ $v\in\mathbb{R}^D$, ở đó $D$ là số lượng từ phân biệt có thể có. Mỗi thành phần toạ độ của $v$ tương ứng với 1 từ và ghi số từ có trong văn bản. Giả sử xét các đoạn văn bản sau:
> * $D_1$: *Tôi là An*.
> * $D_2$: *Tôi thích xem phim*.
> * $D_3$: *An là tên tôi*.
> * $D_4$: *Tôi rất rất thích đi du lịch, An là tên tôi*.

* Viết toạ độ của các văn bản trong không gian 11 chiều với toạ độ tương ứng với danh sách các từ sau:
> (*An, du, đi, là, lịch, phim, rất, tên, thích, tôi, xem*)
* Tính khoảng cách Euclide giữa các văn bản $D_1,D_2,D_3$, và $D_4$.


In [8]:
d1 = np.array([1,0,0,1,0,0,0,0,0,1,0])
d2 = np.array([0,0,0,0,0,1,0,0,1,1,1])
d3 = np.array([1,0,0,1,0,0,0,1,0,1,0])
d4 = np.array([1,1,1,1,1,0,2,1,1,2,0])
D = np.vstack([d1,d2,d3,d4])
for i in range(len(D)):
    for j in range(i+1,len(D)):
        print('Khoảng cách d{} và d{} là'.format(i+1,j+1), np.linalg.norm(D[i]-D[j]))

Khoảng cách d1 và d2 là 2.23606797749979
Khoảng cách d1 và d3 là 1.0
Khoảng cách d1 và d4 là 3.1622776601683795
Khoảng cách d2 và d3 là 2.449489742783178
Khoảng cách d2 và d4 là 3.605551275463989
Khoảng cách d3 và d4 là 3.0
