In [16]:
import numpy as np

In [17]:
x=np.array([5,15,25,35,45,55])
y=np.array([5,20,14,32,22,38])
print(x,y)

[ 5 15 25 35 45 55] [ 5 20 14 32 22 38]


In [18]:
A=np.vstack([np.ones(len(x)),x]).T
print(A)

[[ 1.  5.]
 [ 1. 15.]
 [ 1. 25.]
 [ 1. 35.]
 [ 1. 45.]
 [ 1. 55.]]


In [19]:
beta=np.linalg.pinv(A)@y
print(beta)

[5.63333333 0.54      ]


In [20]:
beta=np.linalg.lstsq(A,y)[0]
print(beta)

[5.63333333 0.54      ]


C:\Users\Admin\AppData\Local\Temp\ipykernel_24640\3160162078.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  beta=np.linalg.lstsq(A,y)[0]


In [21]:
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x.reshape(-1,1), y)
print(model.intercept_,model.coef_)

5.633333333333329 [0.54]


In [22]:
def MSE(y,y_pred):
    MSE=np.mean((y-y_pred)**2)
    return MSE

In [23]:
y_pred=beta[0]+beta[1]*x
MSE(y,y_pred)

33.75555555555555

In [22]:
A=np.vstack([np.ones(len(x)),x,x**2]).T
print(A)

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


In [23]:
beta=np.linalg.pinv(A)@y
print(beta)

[ 4.43839286e+00  6.57857143e-01 -1.96428571e-03]


In [24]:
y_pred=beta[0]+beta[1]*x+beta[2]*x**2
MSE(y,y_pred)

33.515476190476186

In [1]:
import numpy as np
from numpy.linalg import inv as inv
from numpy.linalg import pinv as pinv
from numpy.linalg import lstsq

In [2]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
np.linalg.matrix_rank(A)

2

In [4]:
pinv(A)

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02,  3.36727575e-17,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [5]:
A=np.array([1,1,1,1]).reshape(2,2)
print(pinv(A))

[[0.25 0.25]
 [0.25 0.25]]


In [6]:
A@pinv(A)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [7]:
pinv(A)@A

array([[0.5, 0.5],
       [0.5, 0.5]])

In [8]:
A=np.array([1,0,0,1,0,1]).reshape(3,2)
print(A)

[[1 0]
 [0 1]
 [0 1]]


In [9]:
pinv(A)

array([[1. , 0. , 0. ],
       [0. , 0.5, 0.5]])

In [10]:
A=np.array([1,-6,1,-2,1,1,1,7]).reshape(4,2)
print(A)

[[ 1 -6]
 [ 1 -2]
 [ 1  1]
 [ 1  7]]


In [11]:
b=np.array([-1,2,1,6])
print(b)

[-1  2  1  6]


In [12]:
z=pinv(A)@b
print(z)

[2.  0.5]


In [14]:
lstsq(A,b)[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_24640\1814808541.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  lstsq(A,b)[0]


array([2. , 0.5])

In [15]:
lstsq(A,b)

C:\Users\Admin\AppData\Local\Temp\ipykernel_24640\3582444113.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  lstsq(A,b)


(array([2. , 0.5]), array([3.5]), 2, array([9.48683298, 2.        ]))