In [2]:
import numpy as np
import pandas as pd

In [3]:
import os
from PIL import Image
import matplotlib.pyplot as plt
%matplotlib inline

## Thực hành 1
Cho ma trận $$A=\begin{pmatrix}
2&1&3\\ 1&2&0
\end{pmatrix} $$


a) Thực hiện phép phân tích SVD.

b) Tính ma trận nghịch đảo suy rộng của $A$.


In [5]:
A=np.array([[2,1,3],[1,2,0]])
print(A)

[[2 1 3]
 [1 2 0]]


In [8]:
u,s,vt=np.linalg.svd(A)
print(u)
print(s)
print(vt)

[[-0.9347217  -0.35538056]
 [-0.35538056  0.9347217 ]]
[3.93964431 1.8652621 ]
[[-0.56472711 -0.41767294 -0.71178129]
 [ 0.12006923  0.81171587 -0.57157741]
 [-0.81649658  0.40824829  0.40824829]]


In [18]:
m,n=A.shape
d=np.zeros((m,n))
for i in range(min(m,n)):
    d[i,i]=s[i]
print(d)

[[3.93964431 0.         0.        ]
 [0.         1.8652621  0.        ]]


In [21]:
print(u.dot(d.dot(vt))) # A=u*d*vt

[[2. 1. 3.]
 [1. 2. 0.]]


In [23]:
m,n=A.shape
invd=np.zeros((n,m))
for i in range(min(m,n)):
    if np.abs(s[i])>1e-6:
        invd[i,i]=1/s[i]
print(invd)

[[0.25383002 0.        ]
 [0.         0.53611768]
 [0.         0.        ]]


In [24]:
Ad=vt.T.dot(invd.dot(u.T))
print(Ad)

[[ 0.11111111  0.11111111]
 [-0.05555556  0.44444444]
 [ 0.27777778 -0.22222222]]


In [26]:
np.linalg.pinv(A)

array([[ 0.11111111,  0.11111111],
       [-0.05555556,  0.44444444],
       [ 0.27777778, -0.22222222]])

## Thực hành 2
Sử dụng thư viện $numpy.linalg.svd$ tìm khai triển SVD cho ma trận $$A=\begin{pmatrix}
1&0&0&0&2\\
0&0&3&0&0\\
0&0&0&0&0\\
0&2&0&0&0
\end{pmatrix} $$

In [4]:
A=np.zeros((4,5))
A[0,0]=1
A[0,4]=2
A[1,2]=3
A[3,1]=2
print(A)

[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]


In [5]:
u,s,vt=np.linalg.svd(A)
print(u)
print(s)
print(vt)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]]
[3.         2.23606798 2.         0.        ]
[[-0.          0.          1.          0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [-0.          1.          0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]


In [32]:
m,n=A.shape
d=np.zeros((m,n))
for i in range(min(m,n)):
    d[i,i]=s[i]
print(d)

[[3.         0.         0.         0.         0.        ]
 [0.         2.23606798 0.         0.         0.        ]
 [0.         0.         2.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [33]:
u.dot(d.dot(vt))

array([[1., 0., 0., 0., 2.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.]])