# Bài thực hành 4
### Môn: Linear Algebra

In [1]:
import numpy as np
from scipy import linalg
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

In [2]:
# Phương pháp khử Gauss - Jordan
def gauss_jordan(A):
    m,n = A.shape
    pivots=[]
    s=-1
    for j in range(n):
        col = A[:,j].copy()
        for i in pivots:
            col[i] = 0
        col = np.abs(col)
        pivot_arg = np.argmax(col)
        pivot = A[pivot_arg,j]
        if col[pivot_arg]!=0 and s<m-1:
            s+=1
            pivots.append(s)
            A[pivot_arg,:] = 1/pivot*A[pivot_arg,:]
            row_swap = A[s,:].copy()
            A[s,:] = A[pivot_arg,:]
            A[pivot_arg,:] = row_swap
            for i in range(m):
                if i!=s:
                    A[i,:] -= A[i,j]*A[s,:]

### Bài tập 1
Cho hai không gian $U_1$ và $U_2$, trong đó $U_1$ được sinh bởi các cột của ma trận ${\bf A}_1$, $U_2$ được sinh bởi các cột của ma trận ${\bf A}_2$ với

$${\bf A}_1=\left[\begin{matrix}
1 & 0 & 1\\
1 & -2 & -1\\
2 & 1 & 3\\
1 & 0 & 1
\end{matrix}\right],\ 
{\bf A}_2=\left[\begin{matrix}
3 & -3 & 0\\
1 & 2 & 3\\
7 & -5 & 2\\
3 & -1 & 2
\end{matrix}\right]$$

Xác định một cơ sở và số chiều của các không gian véc tơ sau đây:
* $U_1$, $U_2$.
* $U_3=U_1+U_2=\{x=x_1+x_2\,:\,x_1\in U_1,\,x_2\in U_2\}$.
* $U_4=U_1\cap U_2=\{x\,:\,x\in U_1,\,x\in U_2\}$.

In [3]:
A1 = np.array([1,0,1,1,-2,-1,2,1,3,1,0,1],dtype=np.float).reshape(4,3)
A2 = np.array([3,-3,0,1,2,3,7,-5,2,3,-1,2],dtype=np.float).reshape(4,3)
print(A1,A2,sep='\n')

[[ 1.  0.  1.]
 [ 1. -2. -1.]
 [ 2.  1.  3.]
 [ 1.  0.  1.]]
[[ 3. -3.  0.]
 [ 1.  2.  3.]
 [ 7. -5.  2.]
 [ 3. -1.  2.]]


<ipython-input-3-0d4fa03b3d83>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A1 = np.array([1,0,1,1,-2,-1,2,1,3,1,0,1],dtype=np.float).reshape(4,3)
<ipython-input-3-0d4fa03b3d83>:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A2 = np.array([3,-3,0,1,2,3,7,-5,2,3,-1,2],dtype=np.float).reshape(4,3)


In [4]:
# Cơ sở và số chiều của U1
print("dim(U1) = ",np.linalg.matrix_rank(A1))
print(linalg.lu(A1)[2])
print("Cơ sở của U1 là:")
print("u1 =",A1[:,0].flatten())
print("u2 =",A1[:,1].flatten())

# Cơ sở và số chiều của U2
print("dim(U2) = ",np.linalg.matrix_rank(A2))
print(linalg.lu(A2)[2])
print("Cơ sở của U2 là:")
print("u3 =",A2[:,0].flatten())
print("u4 =",A2[:,1].flatten())

dim(U1) =  2
[[ 2.00000000e+00  1.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00 -2.50000000e+00 -2.50000000e+00]
 [ 0.00000000e+00  0.00000000e+00  2.77555756e-17]]
Cơ sở của U1 là:
u1 = [1. 1. 2. 1.]
u2 = [ 0. -2.  1.  0.]
dim(U2) =  2
[[ 7.00000000e+00 -5.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  2.71428571e+00  2.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.34242658e-17]]
Cơ sở của U2 là:
u3 = [3. 1. 7. 3.]
u4 = [-3.  2. -5. -1.]


In [5]:
# Cơ sở và số chiều của U3
A3 = np.hstack([A1,A2])
print(A3)
A3_=A3.copy()
gauss_jordan(A3_)
print(A3_)
print("dim(U3) = ",np.linalg.matrix_rank(A3_))
print("Cơ sở của U3 là:",A3[:,0].flatten(),
      A3[:,1].flatten(),A3[:,4].flatten(),sep='\n')

[[ 1.  0.  1.  3. -3.  0.]
 [ 1. -2. -1.  1.  2.  3.]
 [ 2.  1.  3.  7. -5.  2.]
 [ 1.  0.  1.  3. -1.  2.]]
[[ 1.  0.  1.  3.  0.  3.]
 [-0.  1.  1.  1.  0.  1.]
 [-0. -0. -0. -0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.]]
dim(U3) =  3
Cơ sở của U3 là:
[1. 1. 2. 1.]
[ 0. -2.  1.  0.]
[-3.  2. -5. -1.]


In [6]:
# Cơ sở và số chiều của U3
A4 = np.hstack([A1[:,:2],-A2[:,:2]])
print(A4)
A4_=A4.copy()
gauss_jordan(A4_)
print(A4_)
print("dim(U4) = ",len(A4_)-np.linalg.matrix_rank(A4_))
print("Cơ sở của U4 là:",(A4[:,2]-A4_[2,2]*A4[:,3]).flatten())

[[ 1.  0. -3.  3.]
 [ 1. -2. -1. -2.]
 [ 2.  1. -7.  5.]
 [ 1.  0. -3.  1.]]
[[ 1.  0. -3.  0.]
 [-0.  1. -1.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  0.]]
dim(U4) =  1
Cơ sở của U4 là: [-3. -1. -7. -3.]


### Bài tập 2
Cho các đa thức: 
$${\bf p}_1(x)=1+x,\,{\bf p}_2(x)=1-x,\,{\bf p}_3(x)=4$$
$${\bf p}_4(x)=1+x^2,\,{\bf p}_5(x)=1+2x+x^2$$

Gọi $H$ là không gian con của $\mathbb{P}_5$ sinh bởi tập $S=\{{\bf p}_1,{\bf p}_2,{\bf p}_3,{\bf p}_4,{\bf p}_5\}$.

* Hãy tìm một cơ sở và số chiều của $H$.
* Tìm tọa độ của ${\bf q}=3-2x+x^2\in H$ theo cơ sở tìm được.

In [7]:
p1 = np.array([1,1,0])
p2 = np.array([1,-1,0])
p3 = np.array([4,0,0])
p4 = np.array([1,0,1])
p5 = np.array([1,2,1])
H = np.vstack([p1,p2,p3,p4,p5]).T
print(H)
print("dim(H) = ",np.linalg.matrix_rank(H))
U = linalg.lu(H)[2]
print(U)
print("Một cơ sở của H:")
print("p1 = %d + %d.x + %d.x^2"%tuple(p1))
print("p2 = %d + %d.x + %d.x^2"%tuple(p2))
print("p4 = %d + %d.x + %d.x^2"%tuple(p4))
q = np.array([3,-2,1])
sol=np.linalg.solve(np.vstack([p1,p2,p4]).T,q)
print("Tọa độ véc tơ q = %d + %d.x + %d.x^2 là"%tuple(q),tuple(sol))

[[ 1  1  4  1  1]
 [ 1 -1  0  0  2]
 [ 0  0  0  1  1]]
dim(H) =  3
[[ 1.  1.  4.  1.  1.]
 [ 0. -2. -4. -1.  1.]
 [ 0.  0.  0.  1.  1.]]
Một cơ sở của H:
p1 = 1 + 1.x + 0.x^2
p2 = 1 + -1.x + 0.x^2
p4 = 1 + 0.x + 1.x^2
Tọa độ véc tơ q = 3 + -2.x + 1.x^2 là (0.0, 2.0, 1.0)


### Bài 3
Trong xử lý tín hiệu số, phương trình sai phân cấp $n$:

$$y_{k+3}-2y_{k+2}+9y_{k+1}-18y_k=z_k$$

mô tả một bộ lọc tuyến tính với $\{y_k\}$ là tín hiệu vào và $\{z_k\}$ là tín hiệu ra. Trường hợp $z_k=0$ phương trình được gọi là thuần nhất. Tập tín hiệu vào $\{y_k\}$ thoả mãn phương trình thuần nhất là một không gian véc tơ 3 chiều $H$. Xét tập tín hiệu 

$$(\mathcal{B})=\left\{2^k,\,3^k\sin\left(\frac{k\pi}{2}\right),\,3^k\cos\left(\frac{k\pi}{2}\right)\right\}$$

* Chứng minh $(\mathcal{B})$ gồm các nghiệm của phương trình thuần nhất.
* Chứng minh $(\mathcal{B})$ là một cơ sở của $H$.

#### Đáp án:
* Thay trực tiếp vào phương trình
* Chứng minh $(\mathcal{B})$ là hệ độc lập tuyến tính, từ đó suy ra cơ sở. Đặt

$$u_k=2^k,\,v_k=3^k\sin\left(\frac{k\pi}{2}\right),\,w_k=3^k\cos\left(\frac{k\pi}{2}\right)$$

Ta sẽ chứng minh 
$$c_1 u_k+c_2 v_k+c_3 w_k=0$$ 
đúng với mọi $k$ thì $c_1=c_2=c_3=0$. Thay $k$ tương ứng bởi $k$, $k+1$, $k+2$ ta thu được hệ phương trình:
$$
\begin{pmatrix}
u_k & v_k & w_k \\
u_{k+1} & v_{k+1} & w_{k+1} \\
u_{k+2} & v_{k+2} & w_{k+2}
\end{pmatrix}
\begin{pmatrix}
c_1 \\
c_2 \\
c_3 
\end{pmatrix} = 
\begin{pmatrix}
0 \\
0 \\
0
\end{pmatrix}
$$

In [8]:
# Chọn k = 0
A = np.array([[1,0,1],[2,3,0],[4,0,-9]])
detA = np.linalg.det(A)

# Vì detA khác 0 nên suy ra c1 = c2 = c3 = 0. 