# Bài thực hành 2
### Môn: Linear Algebra

In [2]:
import numpy as np

### Bài tập 1
Cho ma trận ${ A}=\left[\begin{matrix}
0 & 0 & 0\\
1 & 0 & 0\\
0 & 1 & 0
\end{matrix}\right]\ \ ;\ \ { B}=\left[\begin{matrix}
4 & -2 & 1\\
3 & 1 & -1\\
-1 & 5 & 0
\end{matrix}\right]$

* Chứng tỏ rằng ${A}^3=0$. Tính $({I}-{A})({I}+{A}+{A}^2)$.
* Tạo ma trận khối $C=\left[\begin{matrix}
A & I\\
-I & B
\end{matrix}\right]$. Tính định thức và hạng của $C$.

In [6]:
A = np.array([0,0,0,1,0,0,0,1,0]).reshape(3,3)
B = np.array([4,-2,1,3,1,-1,-1,5,0]).reshape(3,3)

A_3 = np.linalg.matrix_power(A,3)
K = np.zeros((3,3))
if not np.allclose(B,K): print("B==K")
else: print("B!=K")

B==K


In [15]:
I = np.identity(3)

C1 = np.concatenate([A,I], axis=1)
C2 = np.concatenate([-I,B], axis=1)
C = np.concatenate([C1,C2], axis=0)

C = np.block([[A,I],[-I,B]])

print("det(C) =",np.linalg.det(C))
print("rank(C) =",np.linalg.matrix_rank(C))

det(C) = -0.9999999999999998
rank(C) = 6


### Bài tập 2
Lũy thừa ma trận có thể được sử dụng như một công cụ để phân tích trạng thái tới hạn của một số hệ động lực. Cho hai ma trận sau đây:

$${\bf A}=\left[\begin{matrix}
0.4 & 0.2 & 0.3\\
0.3 & 0.6 & 0.3\\
0.3 & 0.2 & 0.4
\end{matrix}\right],\,{\bf B}=\left[\begin{matrix}
0 & 0.2 & 0.3\\
0.1 & 0.6 & 0.3\\
0.9 & 0.2 & 0.4
\end{matrix}\right]$$

Hãy kiểm tra xem điều gì sẽ xảy ra với ${\bf A}^k$ và ${\bf B}^k$ khi $k$ nhận giá trị lớn.

In [20]:
A = np.array([0.4,0.2,0.3,0.3,0.6,0.3,0.3,0.2,0.4]).reshape(3,3)
B = np.array([0,  0.2,0.3,0.1,0.6,0.3,0.9,0.2,0.4]).reshape(3,3)


k = 1000009

print(np.linalg.matrix_power(A,k))
print(np.linalg.matrix_power(B,k))



[[0.28571429 0.28571429 0.28571429]
 [0.42857143 0.42857143 0.42857143]
 [0.28571429 0.28571429 0.28571429]]
[[0.20224719 0.20224719 0.20224719]
 [0.37078652 0.37078652 0.37078652]
 [0.42696629 0.42696629 0.42696629]]


### Bài 3
Phân tích ma trận đánh giá
$${\bf X}=\left[\begin{matrix}
3 & 3 & 0 & 4 & 4\\
0 & 5 & 2 & 0 & 1\\
2 & 0 & 1 & 2 & 5 \\
0 & 3 & 2 & 5 & 0 \\
2 & 5 & 0 & 3 & 2
\end{matrix}\right]
$$
thành tích $\bf W\,H^T$, với ${\bf W}\in\mathbb{R}^{5\times 3}$, ${\bf H}\in\mathbb{R}^{5\times 3}$. Sử dụng hàm mất mát dạng:
$$\mathcal{L}({\bf W},{\bf H})=\sum_{(u,i):x_{ui}\neq 0}\left(x_{ui}-\sum^3_{j=1}w_{uj}h_{ij}\right)^2$$

In [ ]:
def MF(A, W, H, K, steps=1000, beta=0.002):
    m, n = A.shape
    for step in range(steps): # Bước lặp
        for i in range(m):    # Cập nhật lại ma trận W, H
            for j in range(n):
                if A[i,j]!=0:
                    eij = A[i,j] - W[i]@H[j]
                    for k in range(K):
                        W[i,k] += beta*(2*eij*H[j,k])
                        H[j,k] += beta*(2*eij*W[i,k])
        e = 0 # Tính tổng bình phương sai số
        for i in range(m):
            for j in range(n):
                if A[i,j]!=0:
                    e += (A[i,j] - W[i]@H[j])**2
        if e<1e-5: break  # Điều kiện dừng
    return W, H

In [23]:
X = np.array([3, 3, 0, 4, 4,
              0, 5, 2, 0, 1,
              2, 0, 1, 2, 5,
              0, 3, 2, 5, 0,
              2, 5, 0, 3, 2]).reshape(5,5)
print(X)
M, N = X.shape
print(M, N)
K = 2
W = np.random.rand(M,K)
H = np.random.rand(N,K)
print(W,H)

print(W@H.T)

[[3 3 0 4 4]
 [0 5 2 0 1]
 [2 0 1 2 5]
 [0 3 2 5 0]
 [2 5 0 3 2]]
5 5
[[0.25744788 0.5080927 ]
 [0.50599638 0.28453607]
 [0.44614224 0.98381872]
 [0.50989962 0.06342915]
 [0.77501102 0.67868878]] [[0.83803578 0.03518666]
 [0.23566819 0.6074285 ]
 [0.05678238 0.83432135]
 [0.59671147 0.81258288]
 [0.67076735 0.62573827]]
[[0.23362862 0.36930226 0.43853109 0.56648953 0.49062068]
 [0.43405494 0.29208257 0.2661262  0.53314298 0.51745096]
 [0.40850045 0.70274106 0.84615398 1.06565244 0.91487067]
 [0.42954599 0.15869579 0.08187361 0.35580439 0.38171406]
 [0.67336775 0.59490035 0.61025152 1.01394885 0.94453363]]
