In [1]:
import numpy as np
import pandas as pd
from numpy import linalg as LA

## Thực hành 1 Thuật toán Lee-Seung
Cho ma trận không âm $X$. 

Thực hiện thuật toán Lee-Seung với $k=3$ tìm $W$, $H$ để $X\approx WH$.


In [2]:
data=pd.read_csv("topicmodeling.csv")

In [3]:
data

singer  GDP  senate  election  vote  stock  bass  market  band
0       6    1       1         0     0      1     9       0     8
1       1    0       9         5     8      1     0       1     0
2       8    1       0         1     0      0     9       1     7
3       0    7       1         0     0      9     1       7     0
4       0    5       6         7     5      6     0       7     2
5       1    0       8         5     9      2     0       0     1

In [4]:
data.shape

(6, 9)

In [5]:
X=data.values

In [6]:
Xt=np.transpose(X)

# Khai trien SVD

In [7]:
XXt=np.dot(X,Xt)

In [8]:
XtX=np.dot(Xt,X)

In [9]:
S,U=np.linalg.eigh(XXt)

In [10]:
S

array([  1.86230894,   4.10586676,  13.17603369, 202.53710898,
       354.36496614, 558.95371549])

In [11]:
U[:,-1]

array([-0.2439383 , -0.46526843, -0.24282838, -0.31695293, -0.58262128,
       -0.47449665])

In [12]:
S,V=np.linalg.eigh(XtX)

In [13]:
S

array([-2.37539162e-14, -9.48765698e-15,  1.21340842e-14,  1.86230894e+00,
        4.10586676e+00,  1.31760337e+01,  2.02537109e+02,  3.54364966e+02,
        5.58953715e+02])

In [14]:
V[:,-1]

array([-0.18382475, -0.23764891, -0.50925916, -0.38152126, -0.46128206,
       -0.33865306, -0.19870624, -0.29629711, -0.22379659])

In [15]:
U,S,V=np.linalg.svd(X)

In [16]:
U.shape

(6, 6)

In [17]:
S

array([23.642202  , 18.82458409, 14.23155329,  3.62988067,  2.02629385,
        1.3646644 ])

In [18]:
V

array([[-0.18382475, -0.23764891, -0.50925916, -0.38152126, -0.46128206,
        -0.33865306, -0.19870624, -0.29629711, -0.22379659],
       [ 0.46812431,  0.012264  , -0.22468896, -0.14828941, -0.24669275,
        -0.07055157,  0.62869331, -0.05338785,  0.49426104],
       [-0.13259131,  0.46797765, -0.30354013, -0.14442013, -0.37283256,
         0.51849628, -0.04443082,  0.48542691, -0.07047543],
       [-0.05724682, -0.03721719, -0.21805897,  0.70455642, -0.26126021,
        -0.41873255, -0.16663567,  0.35792771,  0.22784792],
       [ 0.65019475,  0.03176101, -0.01964265, -0.01724685,  0.03372222,
        -0.23146601,  0.02931888,  0.31092311, -0.65062144],
       [ 0.25041509,  0.00379506, -0.67910488,  0.20855589,  0.48716224,
         0.28574645, -0.22743407, -0.24045481,  0.06384377],
       [-0.46269538,  0.03756733, -0.2490279 ,  0.21208289,  0.21525207,
        -0.07608221,  0.68761287, -0.00240234, -0.3906001 ],
       [-0.08535656, -0.7429813 , -0.10677232, -0.22676324,  0

In [19]:
D=np.diag(S)

In [20]:
V.shape

(9, 9)

In [21]:
D.shape

(6, 6)

In [22]:
np.dot(U,np.dot(D,V[:6]))

array([[ 6.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -2.45103915e-16, -2.38217650e-15,  1.00000000e+00,
         9.00000000e+00,  2.54487120e-15,  8.00000000e+00],
       [ 1.00000000e+00,  4.24611036e-15,  9.00000000e+00,
         5.00000000e+00,  8.00000000e+00,  1.00000000e+00,
        -1.06234493e-15,  1.00000000e+00, -8.88178420e-16],
       [ 8.00000000e+00,  1.00000000e+00,  5.71915519e-15,
         1.00000000e+00,  5.16762326e-15, -1.11701246e-15,
         9.00000000e+00,  1.00000000e+00,  7.00000000e+00],
       [-8.68221790e-16,  7.00000000e+00,  1.00000000e+00,
         2.82472438e-15,  4.63438400e-16,  9.00000000e+00,
         1.00000000e+00,  7.00000000e+00, -4.44089210e-16],
       [ 4.29677750e-17,  5.00000000e+00,  6.00000000e+00,
         7.00000000e+00,  5.00000000e+00,  6.00000000e+00,
        -1.57514926e-15,  7.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  1.55680905e-15,  8.00000000e+00,
         5.00000000e+00,  9.00000000e+00,  2.000000

In [23]:
U2=U[:,:2]
D2=np.diag(S[:2])
V2=V[:2]

In [24]:
np.dot(U2,np.dot(D2,V2))

array([[ 6.74229965,  1.51943954,  0.20972256,  0.40037283, -0.33405694,
         1.09673117,  8.77712695,  1.06078924,  7.29007692],
       [-0.03440554,  2.56025512,  6.58889518,  4.84815852,  6.15781126,
         4.03510689, -0.57609003,  3.49379247,  0.29046475],
       [ 6.98818029,  1.5197714 ,  0.07602676,  0.31094484, -0.47827792,
         1.05006064,  9.10860995,  1.02442222,  7.54890621],
       [ 1.13460896,  1.77445093,  3.93269036,  2.93585274,  3.58459179,
         2.57428891,  1.16281538,  2.24799112,  1.42057613],
       [ 0.95600128,  3.23219253,  7.77124883,  5.7545071 ,  7.18447315,
         4.90229301,  0.62038095,  4.26107627,  1.41859413],
       [ 0.21874084,  2.61768554,  6.59774853,  4.86391154,  6.1461834 ,
         4.0768851 , -0.24662295,  3.53414075,  0.56422667]])

In [25]:
U2.shape

(6, 2)

In [26]:
V2.shape

(2, 9)

In [27]:
D2.shape

(2, 2)

# Lee and Seung Algortihm

In [28]:
import numpy as np
def seung_objective(X, W, H):
    ''' calculated the non-negative matrix factorization objective ||X-WH||
        
    Usage:
        W, H = seung_update(X, W, H)
    Parameters:
        V: a (d x n)-array containing n observations in the columns
        W: (d x k)-array of non-negative basis images (components)
        H: (k x n)-array of weights, one column for each of the n observations
    Returns:
        F: a scalar objective
    '''    
    d, n = X.shape
    WH = np.dot(W, H)

    F = (X - WH).sum() / (d * n)
    return F
def seung_updateW(V, W, H):
    ''' performs the multiplicative non-negative matrix factorization updates for W
        
    Usage:
        W, H = seung_update(V, W, H)
    Parameters:
        V: a (d x n)-array containing n observations in the columns
        W: (d x k)-array of non-negative basis images (components)
        H: (k x n)-array of weights, one column for each of the n observations
    Returns:
        W: (d x k)-array of updated non-negative basis images (components)
    '''
    
    WH = np.dot(W, H)
    W_new = W * np.dot(V / WH, H.T)
    W_new = W_new / np.sum(W_new, axis=0, keepdims=True)    
    return W_new

def seung_updateH(V, W, H):
    ''' performs the multiplicative non-negative matrix factorization updates
        
    Usage:
        W, H = seung_update(V, W, H)
    Parameters:
        V: a (d x n)-array containing n observations in the columns
        W: (d x k)-array of non-negative basis images (components)
        H: (k x n)-array of weights, one column for each of the n observations
    Returns:
        H: (k x n)-array of updated weights, one column for each of the n observations
    '''
    
    WH = np.dot(W, H)
    H_new = H * np.dot((V / WH).T, W).T
    return H_new


def seung_nmf(V, k, threshold=1e-5, maxiter=500):
    ''' decomposes X into r components by non-negative matrix factorization
        
    Usage:
        W, H = seung_nmf(X, r)
    Parameters:
        V: a (d x n)-array containing n observations in the columns
        k: number of components to extract
        threshold: relative error threshold of the iteration
        maxiter: maximum number of iterations
    Returns:
        W: (d x k)-array of non-negative basis images (components)
        H: (k x n)-array of weights, one column for each of the n observations
    '''
    
    d, n = V.shape
    W = np.random.rand(d, k)
    H = np.random.rand(k, n)
    F = seung_objective(V, W, H)
    
    it_no = 0
    converged = False

    while (not converged) and it_no <= maxiter:
        W_new = seung_updateW(V, W, H)
        H_new = seung_updateH(V, W_new, H)    
        F_new = seung_objective(V, W_new, H_new)

        converged = np.abs(F_new - F) <= threshold 
        W, H = W_new, H_new
        it_no = it_no + 1
    
    return W, H

In [29]:
W,H=seung_nmf(X,k=3)

In [30]:
W

array([[4.75582943e-001, 1.40066459e-043, 3.48095410e-002],
       [1.24248512e-165, 3.47159754e-001, 4.88617687e-034],
       [5.24417057e-001, 2.23691854e-130, 3.57258702e-014],
       [2.83676112e-096, 1.05454317e-194, 5.74695408e-001],
       [2.30342727e-061, 2.91794103e-001, 3.90495051e-001],
       [3.64887779e-082, 3.61046144e-001, 7.92161381e-145]])

In [31]:
H

array([[1.40000000e+001, 1.64532527e+000, 8.78317987e-001,
        1.00000000e+000, 0.00000000e+000, 3.17758478e-021,
        1.79620963e+001, 1.00000000e+000, 1.50000000e+001],
       [2.00000000e+000, 2.36104015e-258, 2.24592099e+001,
        1.70000000e+001, 2.20000000e+001, 3.99583740e+000,
        0.00000000e+000, 1.55790847e+000, 3.00000000e+000],
       [0.00000000e+000, 1.23546747e+001, 1.66247208e+000,
        2.39412573e-125, 2.63377576e-256, 1.50041626e+001,
        1.03790371e+000, 1.34420915e+001, 1.00311812e-015]])

In [32]:
print( np.array_str(W, precision=3, suppress_small=True) )

[[0.476 0.    0.035]
 [0.    0.347 0.   ]
 [0.524 0.    0.   ]
 [0.    0.    0.575]
 [0.    0.292 0.39 ]
 [0.    0.361 0.   ]]


In [33]:
print( np.array_str(H, precision=3, suppress_small=True) )

[[14.     1.645  0.878  1.     0.     0.    17.962  1.    15.   ]
 [ 2.     0.    22.459 17.    22.     3.996  0.     1.558  3.   ]
 [ 0.    12.355  1.662  0.     0.    15.004  1.038 13.442  0.   ]]


In [34]:
LA.norm(X-W.dot(H))

5.012950878753597

In [35]:
print(np.argmax(H[:,:],axis=0))

[0 2 1 1 1 2 0 2 0]


In [36]:
H[0,:]

array([1.40000000e+01, 1.64532527e+00, 8.78317987e-01, 1.00000000e+00,
       0.00000000e+00, 3.17758478e-21, 1.79620963e+01, 1.00000000e+00,
       1.50000000e+01])

In [37]:
a=np.array([
[0.278, 0.   ],
[0.    ,0.34 ],
[0.289 ,0.   ],
[0.267 ,0.   ],
[0.166 ,0.306],
[0.    ,0.354],
])

In [38]:
b=np.array([
[14.    ,14.   ,  2.314 , 1.279 , 0.   , 13.38 , 19.    ,12.776 ,16.76],
[2.    , 0.    ,22.686 ,16.721, 22.   , 5.62  , 0.   ,  3.224  ,1.24  ] 
])

In [39]:
WH=a.dot(b)

In [40]:
print( np.array_str(WH, precision=3, suppress_small=True) )

[[3.892 3.892 0.643 0.356 0.    3.72  5.282 3.552 4.659]
 [0.68  0.    7.713 5.685 7.48  1.911 0.    1.096 0.422]
 [4.046 4.046 0.669 0.37  0.    3.867 5.491 3.692 4.844]
 [3.738 3.738 0.618 0.341 0.    3.572 5.073 3.411 4.475]
 [2.936 2.324 7.326 5.329 6.732 3.941 3.154 3.107 3.162]
 [0.708 0.    8.031 5.919 7.788 1.989 0.    1.141 0.439]]


In [41]:
np.set_printoptions(precision=3)

## Thực hành 2 ALS Algorithm

Cho ma trận không âm $X$. 

Thực hiện thuật toán ALS với $k=3$ tìm $W$, $H$ để $X\approx WH$.

In [42]:
data=pd.read_csv("topicmodeling.csv")

In [43]:
X=data.values
print(X)

[[6 1 1 0 0 1 9 0 8]
 [1 0 9 5 8 1 0 1 0]
 [8 1 0 1 0 0 9 1 7]
 [0 7 1 0 0 9 1 7 0]
 [0 5 6 7 5 6 0 7 2]
 [1 0 8 5 9 2 0 0 1]]


In [44]:
import numpy as np
from numpy.linalg import lstsq

def als(A, k, num_iter=100, init_W = None, init_H = None):
    # Initialize W and H
    if init_W is None:
        W = np.random.rand(np.size(A, 0), k)
    else:
        W = init_W

    if init_H is None:
        H = np.random.rand(k, np.size(A, 1))
    else:
        H = init_H

    # Decompose the input matrix
    for n in range(num_iter):
        # Update H
        # Solve the least squares problem: argmin_H ||WH - A||
        H = lstsq(W, A, rcond = -1)[0]
        # Set negative elements of H to 0
        H[H < 0] = 0

        # Update W
        # Solve the least squares problem: argmin_W.T ||H.TW.T - A.T||
        W = lstsq(H.T, A.T, rcond = -1)[0].T

        # Set negative elements of W to 0
        W[W < 0] = 0

    return W, H

In [45]:
W,H=als(X,k=2)

In [46]:
W

array([[0.000e+00, 4.299e-01],
       [4.307e-01, 0.000e+00],
       [0.000e+00, 4.461e-01],
       [2.581e-01, 4.836e-02],
       [5.080e-01, 3.195e-02],
       [4.304e-01, 3.553e-04]])

In [47]:
H

array([[ 0.581,  6.128, 15.268, 11.278, 14.216,  9.505,  0.   ,  8.256,
         1.375],
       [15.847,  3.095,  0.601,  0.895,  0.   ,  2.025, 20.536,  1.991,
        17.022]])