In [1]:
import numpy as np
#import pandas as pd
#import matplotlib.pyplot as plt

## THỰC HÀNH 

### Thực hành 1
Cho ma trận $$A=\begin{pmatrix}
4&0&-2\\ 2&5&4\\ 0&0&5
\end{pmatrix} $$

a) Sử dụng hàm $eig$ tìm các giá trị riêng và véc-tơ riêng của ma trận $A$.

b) Xây dựng ma trận đường chéo $D$ từ các giá trị riêng.

c) Tìm ma trận $P$ gồm các véc-tơ riêng tương ứng.

d) Thực hiện phép nhân $PDP^{-1}$ và so sánh với $A$.

In [2]:
# Nhap ma tran A
A=np.array([ [4,0,-2],[ 2,5,4], [0,0,5]] )
print(A)

[[ 4  0 -2]
 [ 2  5  4]
 [ 0  0  5]]


In [3]:
lam, P=np.linalg.eig(A)
for i in range(3):
    print('Giá trị riêng: ', lam[i], 'Véc-tơ riêng: ',P[:,i])

Giá trị riêng:  5.0 Véc-tơ riêng:  [0. 1. 0.]
Giá trị riêng:  4.0 Véc-tơ riêng:  [ 0.4472136  -0.89442719  0.        ]
Giá trị riêng:  5.0 Véc-tơ riêng:  [-0.89442719  0.          0.4472136 ]


In [4]:
D=np.diag(lam)
print('Ma trận đường chéo: D= ',D)


Ma trận đường chéo: D=  [[5. 0. 0.]
 [0. 4. 0.]
 [0. 0. 5.]]


In [5]:
print('Ma trận chéo hóa: P=', P)

Ma trận chéo hóa: P= [[ 0.          0.4472136  -0.89442719]
 [ 1.         -0.89442719  0.        ]
 [ 0.          0.          0.4472136 ]]


In [9]:
np.dot(np.dot(P,D),np.linalg.inv(P))

array([[ 4.,  0., -2.],
       [ 2.,  5.,  4.],
       [ 0.,  0.,  5.]])

In [6]:
A-np.dot(np.dot(P,D),np.linalg.inv(P))

array([[ 0.00000000e+00,  0.00000000e+00,  8.88178420e-16],
       [ 2.22044605e-16,  0.00000000e+00,  4.44089210e-16],
       [ 0.00000000e+00,  0.00000000e+00, -8.88178420e-16]])

## Thực hành 2
Cho ma trận $$A=\left[ \begin {array}{cccc} 62&-38&-4&-100\\ -38&36&-2&64\\ -4&-2&2&6\\ -100&64&6&166
\end {array} \right] $$

a) Sử dụng hàm $eigh$ tìm các giá trị riêng và véc-tơ riêng của ma trận $A$.

b) Xây dựng ma trận đường chéo $D$ từ các giá trị riêng.

c) Tìm ma trận $V$ gồm các véc-tơ riêng tương ứng.

d) Thực hiện phép nhân $VDV^{T}$ và so sánh với $A$.

In [7]:
# Nhap ma tran A
A=np.array([ [62,-38,-4,-100], [-38,36,-2,64], [-4,-2,2,6], [-100,64,6,166] ])
print(A)

[[  62  -38   -4 -100]
 [ -38   36   -2   64]
 [  -4   -2    2    6]
 [-100   64    6  166]]


In [8]:
lam, V=np.linalg.eigh(A)
for i in range(4):
    print('Giá trị riêng: ', lam[i], 'Véc-tơ riêng: ',V[:,i])

Giá trị riêng:  0.10521175403373828 Véc-tơ riêng:  [-0.09354703 -0.35128343 -0.92475687  0.11257725]
Giá trị riêng:  1.2355639271298196 Véc-tơ riêng:  [-0.84085969  0.0687872  -0.00642143 -0.53682593]
Giá trị riêng:  12.187592441617749 Véc-tơ riêng:  [ 0.21031118  0.87541219 -0.37970822 -0.21270724]
Giá trị riêng:  252.4716318772186 Véc-tơ riêng:  [-0.48987055  0.32484113  0.02460017  0.80864078]


In [9]:
D=np.diag(lam)
print('Ma trận đường chéo: D= ',D)

Ma trận đường chéo: D=  [[1.05211754e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.23556393e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.21875924e+01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.52471632e+02]]


In [10]:
print('Ma trận chéo hóa: V=', V)

Ma trận chéo hóa: V= [[-0.09354703 -0.84085969  0.21031118 -0.48987055]
 [-0.35128343  0.0687872   0.87541219  0.32484113]
 [-0.92475687 -0.00642143 -0.37970822  0.02460017]
 [ 0.11257725 -0.53682593 -0.21270724  0.80864078]]


In [11]:
np.dot(np.dot(V,D),V.T)

array([[  62.,  -38.,   -4., -100.],
       [ -38.,   36.,   -2.,   64.],
       [  -4.,   -2.,    2.,    6.],
       [-100.,   64.,    6.,  166.]])

In [12]:
A-np.dot(np.dot(V,D),V.T)

array([[ 2.84217094e-14, -1.42108547e-14,  8.88178420e-16,
         1.42108547e-14],
       [-1.42108547e-14,  4.97379915e-14, -1.55431223e-15,
         5.68434189e-14],
       [ 8.88178420e-16, -1.55431223e-15,  2.88657986e-15,
         0.00000000e+00],
       [ 1.42108547e-14,  4.97379915e-14,  0.00000000e+00,
         0.00000000e+00]])

In [13]:
V@V.T

array([[ 1.00000000e+00, -1.40790733e-17,  5.65012955e-17,
        -5.59205409e-17],
       [-1.40790733e-17,  1.00000000e+00,  3.02094904e-17,
         8.02223056e-17],
       [ 5.65012955e-17,  3.02094904e-17,  1.00000000e+00,
        -6.21947479e-17],
       [-5.59205409e-17,  8.02223056e-17, -6.21947479e-17,
         1.00000000e+00]])